"""
Unified Drone Visualizer

This script dynamically loads a JSON configuration file generated by the
optimization scripts, constructs the MuJoCo physics model directly from
the XML, and visualizes the drone using its optimized parameters.
"""

import sys
import json
import argparse
import time
import numpy as np
import mujoco
import mujoco.viewer
import matplotlib.pyplot as plt

# --- Target Maneuver Settings ---
TARGET_POS_X = 1.0
TARGET_POS_Y = 0.5
TARGET_POS_Z_START = 0.05
TARGET_POS_Z_END = 1.5
TARGET_PITCH_DEG = 0.0
TARGET_ROLL_DEG = 0.0
TARGET_YAW_DEG = 45.0

def quat_mult(q1, q2):
    w1, x1, y1, z1 = q1
    w2, x2, y2, z2 = q2
    return np.array([
        w1*w2 - x1*x2 - y1*y2 - z1*z2,
        w1*x2 + x1*w2 + y1*z2 - z1*y2,
        w1*y2 - x1*z2 + y1*w2 + z1*x2,
        w1*z2 + x1*y2 - y1*x2 + z1*w2
    ])

def quat_conj(q):
    return np.array([q[0], -q[1], -q[2], -q[3]])

def apply_quat(q, v):
    vq = np.array([0.0, v[0], v[1], v[2]])
    res = quat_mult(quat_mult(q, vq), quat_conj(q))
    return res[1:]

def main():
    parser = argparse.ArgumentParser(description="Visualize drone configuration from JSON.")
    parser.add_argument("--model", type=str, required=True, help="Path to MuJoCo XML file.")
    parser.add_argument("--config", type=str, default=None, help="Optional: Path to JSON config file. If not provided, it is auto-inferred from the model name.")
    args = parser.parse_args()
    
    import os
    if args.config:
        config_path = args.config
    else:
        xml_name = os.path.splitext(os.path.basename(args.model))[0]
        config_path = os.path.join("output", f"{xml_name}_opt.json")
    
    try:
        with open(config_path, "r") as f:
            config = json.load(f)
    except Exception as e:
        print(f"Error loading {config_path}: {e}")
        return

    try:
        model = mujoco.MjModel.from_xml_path(args.model)
    except ValueError as e:
        print(f"Error loading model {args.model}: {e}")
        return

    data = mujoco.MjData(model)
    
    num_id1 = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_NUMERIC, "transport_delay_ms")
    transport_delay_ms = model.numeric_data[model.numeric_adr[num_id1]] if num_id1 != -1 else 110.0
    num_id2 = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_NUMERIC, "motor_tau")
    motor_tau = model.numeric_data[model.numeric_adr[num_id2]] if num_id2 != -1 else 0.085

    drone_body_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "drone")
    
    mixer = np.array(config["mixer_matrix"])
    Kp = np.array(config["pid_gains"]["Kp"])
    Ki = np.array(config["pid_gains"]["Ki"])
    Kd = np.array(config["pid_gains"]["Kd"])
    Kp_x, Kd_x, Kp_y, Kd_y = config["outer_gains"]
    
    if "max_int" in config:
        max_int = np.array(config["max_int"])
    else:
        max_int = np.array([2.0, 2.0, 2.0, 2.0])
    
    if "dof_mask" in config:
        dof_mask = np.array(config["dof_mask"])
    else:
        num_id_dof = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_NUMERIC, "dof_mask")
        if num_id_dof != -1:
            adr = model.numeric_adr[num_id_dof]
            size = model.numeric_size[num_id_dof]
            dof_mask = model.numeric_data[adr:adr+size].copy()
            if len(dof_mask) < 6:
                dof_mask = np.pad(dof_mask, (0, 6 - len(dof_mask)), constant_values=0)
        else:
            dof_mask = np.array([0, 0, 1, 1, 1, 1])
    
    mass = model.body_mass[drone_body_id]
    
    max_thrusts = model.actuator_ctrlrange[:, 1]
    min_thrusts = model.actuator_ctrlrange[:, 0]
    safe_max_thrusts = max_thrusts + 1e-6
    num_motors = model.nu
    
    if len(config["motors"]) != num_motors:
        raise ValueError(f"Mismatch: config was optimized for {len(config['motors'])} motors, but XML model '{args.xml}' has {num_motors} actuators. Please provide the correct --xml argument.")

    mujoco.mj_resetData(model, data)
    data.qpos[:3] = [0.0, 0.0, TARGET_POS_Z_START]
    data.qpos[3:7] = [1.0, 0.0, 0.0, 0.0]
    mujoco.mj_forward(model, data)
    
    dt = model.opt.timestep
    steps = int(20.0 / dt)
    
    delay_steps = int((transport_delay_ms / 1000.0) / dt)
    delay_steps = max(1, delay_steps)
    alpha_motor = dt / (motor_tau + dt)
    
    integral_error_z = 0.0
    integral_error_ang = np.zeros(3)
    
    base_thrusts = mixer @ np.array([mass * 9.81, 0.0, 0.0, 0.0])
    actual_motor_pwm = np.sign(base_thrusts) * np.sqrt(np.abs(base_thrusts) / safe_max_thrusts)
    actual_motor_pwm_arr = actual_motor_pwm.copy()
    action_queue = [actual_motor_pwm_arr.copy()] * delay_steps
    
    viewer = mujoco.viewer.launch_passive(model, data)
    
    history_t = []
    
    history_x = []
    history_target_x = []
    history_y = []
    history_target_y = []
    history_z = []
    history_target_z = []
    
    history_roll = []
    history_target_roll = []
    history_pitch = []
    history_target_pitch = []
    history_yaw = []
    history_target_yaw = []
    history_thrusts = []
    
    target_x = TARGET_POS_X
    target_y = TARGET_POS_Y
    target_yaw_deg = TARGET_YAW_DEG
    
    print(f"Loaded Drone Configuration: {num_motors} motors from {args.model}")
    print("Launching MuJoCo viewer. The flight will take exactly 5 seconds...")
    
    for step in range(steps):
        t = step * dt
        t_rise = 2.0
        
        # 20-second Waypoint Trajectory
        # 0-3s: Takeoff to Z=1.0m
        # 3-6s: Hover
        # 6-10s: Diagonal 2D move (X=0.5, Y=0.5), Yaw to 45 deg
        # 10-14s: Diagonal 3D move (X=-0.5, Y=1.0, Z=2.0)
        # 14-20s: Hover and hold
        
        target_pos = np.array([0.0, 0.0, 0.0])
        target_vel = np.array([0.0, 0.0, 0.0])
        current_target_yaw = 0.0
        target_ang_vel = np.array([0.0, 0.0, 0.0])
        
        def min_jerk(t_curr, duration, p0, p1):
            if t_curr <= 0: return p0, 0.0
            if t_curr >= duration: return p1, 0.0
            tau = t_curr / duration
            s = 10*tau**3 - 15*tau**4 + 6*tau**5
            ds = (30*tau**2 - 60*tau**3 + 30*tau**4) / duration
            return p0 + (p1 - p0) * s, (p1 - p0) * ds
            
        if t < 3.0:
            pz, vz = min_jerk(t, 3.0, 0.0, 1.0)
            target_pos = np.array([0.0, 0.0, pz])
            target_vel = np.array([0.0, 0.0, vz])
        elif t < 6.0:
            target_pos = np.array([0.0, 0.0, 1.0])
        elif t < 10.0:
            t_seg = t - 6.0
            px, vx = min_jerk(t_seg, 4.0, 0.0, 0.5)
            py, vy = min_jerk(t_seg, 4.0, 0.0, 0.5)
            pyaw, vyaw = min_jerk(t_seg, 4.0, 0.0, np.radians(45.0))
            target_pos = np.array([px, py, 1.0])
            target_vel = np.array([vx, vy, 0.0])
            current_target_yaw = pyaw
            target_ang_vel = np.array([0.0, 0.0, vyaw])
        elif t < 14.0:
            t_seg = t - 10.0
            px, vx = min_jerk(t_seg, 4.0, 0.5, -0.5)
            py, vy = min_jerk(t_seg, 4.0, 0.5, 1.0)
            pz, vz = min_jerk(t_seg, 4.0, 1.0, 2.0)
            target_pos = np.array([px, py, pz])
            target_vel = np.array([vx, vy, vz])
            current_target_yaw = np.radians(45.0)
        else:
            target_pos = np.array([-0.5, 1.0, 2.0])
            target_vel = np.zeros(3)
            current_target_yaw = np.radians(45.0)
            
            # Inject chirp perturbation during final hover (14-20s)
            t_chirp = t - 14.0
            f0 = 0.5
            k = 1.0
            phase = 2 * np.pi * (f0 * t_chirp + 0.5 * k * t_chirp**2)
            
            chirp_amplitude = 0.05
            chirp_pos = chirp_amplitude * np.sin(phase)
            chirp_vel = chirp_amplitude * 2 * np.pi * (f0 + k * t_chirp) * np.cos(phase)
            
            target_pos[0] += chirp_pos
            target_pos[1] += chirp_pos
            target_vel[0] += chirp_vel
            target_vel[1] += chirp_vel
            
        pos = data.qpos[:3]
        quat = data.qpos[3:7]
        vel = data.qvel[:3]
        ang_vel = data.qvel[3:6]
        
        pos_err = target_pos - pos
        vel_err = target_vel - vel
        
        w, x_quat, y_quat, z_quat = quat
        current_yaw_actual = np.arctan2(2*(w*z_quat + x_quat*y_quat), 1 - 2*(y_quat**2 + z_quat**2))
        cos_y = np.cos(current_yaw_actual)
        sin_y = np.sin(current_yaw_actual)
        
        pos_err_body_x = pos_err[0] * cos_y + pos_err[1] * sin_y
        pos_err_body_y = -pos_err[0] * sin_y + pos_err[1] * cos_y
        vel_err_body_x = vel_err[0] * cos_y + vel_err[1] * sin_y
        vel_err_body_y = -vel_err[0] * sin_y + vel_err[1] * cos_y
        
        max_tilt = np.radians(20.0)
        wrench_dict = {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0}
        
        if dof_mask[0] == 1:
            wrench_dict[0] = (Kp_x * pos_err_body_x + Kd_x * vel_err_body_x) * mass
            target_pitch = np.radians(TARGET_PITCH_DEG)
        else:
            accel_x_cmd = Kp_x * pos_err_body_x + Kd_x * vel_err_body_x
            target_pitch = np.clip(accel_x_cmd / 9.81, -max_tilt, max_tilt)
            
        if dof_mask[1] == 1:
            wrench_dict[1] = (Kp_y * pos_err_body_y + Kd_y * vel_err_body_y) * mass
            target_roll = np.radians(TARGET_ROLL_DEG)
        else:
            accel_y_cmd = Kp_y * pos_err_body_y + Kd_y * vel_err_body_y
            target_roll = np.clip(-accel_y_cmd / 9.81, -max_tilt, max_tilt)
        
        cr, sr = np.cos(target_roll * 0.5), np.sin(target_roll * 0.5)
        cp, sp = np.cos(target_pitch * 0.5), np.sin(target_pitch * 0.5)
        cy, sy = np.cos(current_target_yaw * 0.5), np.sin(current_target_yaw * 0.5)

        target_quat = np.array([
            cr * cp * cy + sr * sp * sy,
            sr * cp * cy - cr * sp * sy,
            cr * sp * cy + sr * cp * sy,
            cr * cp * sy - sr * sp * cy
        ])
        
        q_err = quat_mult(quat_conj(quat), target_quat)
        if q_err[0] < 0: q_err = -q_err
        ang_err = 2.0 * q_err[1:]
        ang_vel_err = target_ang_vel - ang_vel
        
        integral_error_z = np.clip(integral_error_z + pos_err[2] * dt, -max_int[0], max_int[0])
        desired_accel_z = Kp[0]*pos_err[2] + Ki[0]*integral_error_z + Kd[0]*vel_err[2]
        desired_force_z = (desired_accel_z + 9.81) * mass
        
        integral_error_ang = np.clip(integral_error_ang + ang_err * dt, -max_int[1:], max_int[1:])
        desired_ang_accel = Kp[1:]*ang_err + Ki[1:]*integral_error_ang + Kd[1:]*ang_vel_err
        
        diag_I = model.body_inertia[drone_body_id]
        iquat = model.body_iquat[drone_body_id]
        R_inertia = np.zeros(9)
        mujoco.mju_quat2Mat(R_inertia, iquat)
        R_inertia = R_inertia.reshape(3, 3)
        I_body = R_inertia @ np.diag(diag_I) @ R_inertia.T
        gyro_term = np.cross(ang_vel, I_body @ ang_vel)
        desired_torque_body = I_body @ desired_ang_accel + gyro_term
        
        wrench_dict[2] = (desired_accel_z + 9.81) * mass
        wrench_dict[3] = desired_torque_body[0]
        wrench_dict[4] = desired_torque_body[1]
        wrench_dict[5] = desired_torque_body[2]
        
        active_dofs = np.where(dof_mask == 1)[0]
        
        # Attitude wrench
        att_wrench = np.array([wrench_dict[dof] if dof >= 3 else 0.0 for dof in active_dofs])
        thrusts_att = mixer @ att_wrench
        
        max_att = np.max(np.abs(thrusts_att) / (safe_max_thrusts + 1e-6))
        if max_att > 1.0:
            thrusts_att /= max_att
            
        # Position wrench
        pos_wrench = np.array([wrench_dict[dof] if dof < 3 else 0.0 for dof in active_dofs])
        thrusts_pos = mixer @ pos_wrench
        
        scale_pos = 1.0
        for i in range(num_motors):
            if thrusts_pos[i] > 0:
                margin = max_thrusts[i] - thrusts_att[i]
                if margin < 0: margin = 0
                if thrusts_pos[i] > margin:
                    scale_pos = min(scale_pos, margin / thrusts_pos[i])
            elif thrusts_pos[i] < 0:
                margin = min_thrusts[i] - thrusts_att[i]
                if margin > 0: margin = 0
                if thrusts_pos[i] < margin:
                    scale_pos = min(scale_pos, margin / thrusts_pos[i])
                    
        thrusts = thrusts_att + scale_pos * thrusts_pos
        thrusts = np.clip(thrusts, min_thrusts, max_thrusts)
        
        pwm_cmd = np.sign(thrusts) * np.sqrt(np.abs(thrusts) / safe_max_thrusts)
        
        action_queue.append(pwm_cmd)
        delayed_pwm = action_queue.pop(0)
        
        actual_motor_pwm_arr = (1.0 - alpha_motor) * actual_motor_pwm_arr + alpha_motor * delayed_pwm
        physical_thrusts = np.sign(actual_motor_pwm_arr) * (actual_motor_pwm_arr ** 2) * max_thrusts
        
        data.ctrl[:] = physical_thrusts
        mujoco.mj_step(model, data)
        
        if step % (int(0.02 / dt)) == 0:
            history_t.append(t)
            history_x.append(pos[0])
            history_target_x.append(target_pos[0])
            history_y.append(pos[1])
            history_target_y.append(target_pos[1])
            history_z.append(pos[2])
            history_target_z.append(target_pos[2])
            
            w, x, y, z = quat
            actual_roll = np.arctan2(2*(w*x + y*z), 1 - 2*(x**2 + y**2))
            actual_pitch = np.arcsin(2*(w*y - z*x))
            actual_yaw = np.arctan2(2*(w*z + x*y), 1 - 2*(y**2 + z**2))
            
            history_roll.append(np.degrees(actual_roll))
            history_pitch.append(np.degrees(actual_pitch))
            history_yaw.append(np.degrees(actual_yaw))
            
            history_target_roll.append(np.degrees(target_roll))
            history_target_pitch.append(np.degrees(target_pitch))
            history_target_yaw.append(np.degrees(current_target_yaw))
            history_thrusts.append(physical_thrusts.copy())
            
            viewer.sync()
            time.sleep(0.02)
            
    viewer.close()
    
    history_thrusts = np.array(history_thrusts)

    plt.figure(figsize=(15, 12))
    
    # Z (Height)
    plt.subplot(4, 2, 1)
    plt.plot(history_t, history_z, label='Actual Z')
    plt.plot(history_t, history_target_z, 'r--', label='Target Z')
    plt.ylabel('Height Z (m)')
    plt.legend()
    plt.grid(True)
    
    # Roll
    plt.subplot(4, 2, 2)
    plt.plot(history_t, history_roll, label='Actual Roll')
    plt.plot(history_t, history_target_roll, 'g--', label='Cmd Roll (Outer Loop)')
    plt.ylabel('Roll (deg)')
    plt.legend()
    plt.grid(True)

    # X Position
    plt.subplot(4, 2, 3)
    plt.plot(history_t, history_x, label='Actual X')
    plt.plot(history_t, history_target_x, 'r--', label='Target X')
    plt.ylabel('Position X (m)')
    plt.legend()
    plt.grid(True)
    
    # Pitch
    plt.subplot(4, 2, 4)
    plt.plot(history_t, history_pitch, label='Actual Pitch')
    plt.plot(history_t, history_target_pitch, 'g--', label='Cmd Pitch (Outer Loop)')
    plt.ylabel('Pitch (deg)')
    plt.legend()
    plt.grid(True)
    
    # Y Position
    plt.subplot(4, 2, 5)
    plt.plot(history_t, history_y, label='Actual Y')
    plt.plot(history_t, history_target_y, 'r--', label='Target Y')
    plt.ylabel('Position Y (m)')
    plt.xlabel('Time (s)')
    plt.legend()
    plt.grid(True)
    
    # Yaw
    plt.subplot(4, 2, 6)
    plt.plot(history_t, history_yaw, label='Actual Yaw')
    plt.plot(history_t, history_target_yaw, 'r--', label='Target Yaw')
    plt.ylabel('Yaw (deg)')
    plt.xlabel('Time (s)')
    plt.legend()
    plt.grid(True)
    
    # Motor Thrusts
    plt.subplot(4, 2, (7, 8))
    for i in range(num_motors):
        plt.plot(history_t, history_thrusts[:, i], label=f'Motor {i+1}')
    plt.ylabel('Thrust (N)')
    plt.xlabel('Time (s)')
    plt.legend(loc='upper right', ncol=num_motors)
    plt.grid(True)
    
    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    main()
